Disassemble `*.cwasm` for `compile` disas tests  (#8237)
* Disassemble `*.cwasm` for `compile` disas tests

This commit changes how the `compile` mode of the `disas` test suite
works. Previously this would use `--emit-clif` and run the Cranelift
pipeline for each individual function and use the custom VCode-based
disassembly for instruction output. This commit instead uses the raw
binary coming out of Wasmtime. The ELF file itself is parsed and is
disassembled in a manner similar to Winch tests.

The goal of this commit is somewhat twofold:

* Lay the groundwork to migrate all Winch-based filetests to
  `tests/disas`.
* Test the raw output from Cranelift/Wasmtime which includes
  optimizations like branch chomping in the `MachBuffer`.

This commit doesn't itself move the Winch tests yet, that's left for a
future commit.

* Update all test expectations for new output

* Fix PR-based CI when too many files are changed

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -158,7 +158,7 @@ jobs:
         else
           pr=${{ github.event.number }}
           gh pr view $pr --json commits | tee commits.log
-          gh pr diff $pr --name-only | tee names.log
+          gh pr diff $pr --name-only | tee names.log || echo "failed to get files"
           if [ "${{ github.base_ref }}" != "main" ]; then
             run_full=true
           elif grep -q 'prtest:full' commits.log; then
